### ISSUE TITLE
[Improvement, Feature request] Note FX Selector functionality in API

### ISSUE THREAD

**Issue by drakh** [bitwig/bitwig-extensions#47]
createChainSelector() method in my opinon should work for Note FX selector as well.

> const chainSeletor = device.createChainSelector();

//works fine for Instrument Selector, and Audio FX selector, when the chain is Note FX selector, nothing happens

> chainSeletor.exists().addValueObserver((chain) => {
>    // prints if chain is Instrument selector, Audio FX selector, does not print if it is Note FX selector
>     println(JSON.stringify({ chain, c, d })); 
> });

> chainSeletor.activeChainIndex().addValueObserver((chainIdx) => {
>    // prints if chain is Instrument selector, Audio FX selector, does not print if it is Note FX selector
>     println(JSON.stringify({ chainIdx })); 
> }, Constants.NO_NUMBER);

**Comment by abique** [comment]
Fixed in 4.4.2

**Comment by drakh** [comment]
Thank you very much
