### ISSUE TITLE
[Bug] The On/Off macro state is not updated on Akai APC40 MKII when automation is restored

### ISSUE THREAD

**Issue by mcristi** [bitwig/bitwig-extensions#51]
#### Steps to reproduce
1. Add an EQ-DJ on an instrument track.
2. Automate Lo On (or any other ON/OFF macro). The automation macro indicator is red. 
3. Override value on the Lo On button. The automation macro indicator turns green. 
4. Restore Automation Control

#### Expected behavior
The LEDs on AKAI should reflect the macro value. 

#### Actual behavior
The LEDs on AKAI do not reflect the actual macro value. 

#### Notes

If the "Lo On" macro is mapped to a user control knob, the value is correctly reflected when automation is restored. Only on Device control knobs, the value is not reflected. 

Bitwig 4.4.6

**Comment by mcristi** [comment]
With the latest version (5.0), the project layer as well does not refresh the ON/OFF state.

**Comment by mcristi** [comment]
reproduced it in 5.1 as well

**Comment by abique** [comment]
Oh I completely forgot about this issue.
I'll take a look!

**Comment by mcristi** [comment]
This fix will be a significant improvement for my live workflow. Thanks 🎉

**Comment by mcristi** [comment]
Currently just a bedroom project, but hopefully, next year will have the first gig. Will record it for sure.
