### ISSUE TITLE
Expose as artifact on Bitwig Public Maven repo

### ISSUE THREAD

**Issue by jbhurruth** [bitwig/bitwig-extensions#8]
Would it make sense to allow this to be imported via maven for people working on extensions? 

Some of the framework classes seem useful so I attempted to import it as follows without success:

`<dependency>
      <groupId>com.bitwig.extensions</groupId>
      <artifactId>bitwig-extensions</artifactId>
      <version>3.1.2</version>
</dependency>`

**Comment by abique** [comment]
See https://github.com/bitwig/bitwig-extensions/blob/api-17/pom.xml#L12
